theme: jekyll-theme-minimal

title: Coursera-front-end-web-development-course
description: ğŸ“ Assignments for Coursera <a href="https://www.coursera.org/learn/html-css-javascript-for-web-developers">HTML, CSS, and Javascript for Web Developers</a> Course.
